/**
 * Bootstrap Icons - React Components
 *
 * Auto-generated from Bootstrap Icons SVG files.
 * DO NOT EDIT - this file is generated by tools/scripts/icons/generate-icons.cjs
 *
 * @packageDocumentation
 */

// Re-export types
export type { IconComponent, IconProps } from './types';

// Re-export all icon components
export * from './components';
