/**
 * DSAI Configuration for Storybook
 *
 * This configuration tells @dsai/tools where to find your Figma token exports
 * and where to output the generated style files.
 *
 * DIRECTORY STRUCTURE:
 * storybook/
 * ├── src/
 * │   ├── figma-exports/     ← Raw exports from Figma (theme.json, foundation.json, etc.)
 * │   ├── collections/       ← Transformed tokens (generated by dsai tokens transform)
 * │   └── generated/         ← Built output files (CSS, JS, TS, SCSS)
 *
 * WORKFLOW:
 * 1. Export tokens from Figma (Tokens Studio plugin) to: src/figma-exports/
 * 2. Run: pnpm tokens:transform   (converts Figma format → DTCG collections)
 * 3. Run: pnpm tokens:build       (builds collections → CSS/JS/TS/SCSS)
 * 4. Run: pnpm scss:build         (compiles Bootstrap theme with tokens)
 * 5. Import generated styles in preview.ts from src/generated/
 *
 * @see https://github.com/michelve/dsai/tree/main/packages/@dsai/tools
 */

import { defineConfig } from '@dsai/tools';

export default defineConfig({
  // Global settings
  global: {
    debug: process.env['DEBUG'] === 'true',
    logLevel: process.env['LOG_LEVEL'] ?? 'info',
  },

  // Token configuration
  tokens: {
    // Source type - 'theme' uses theme.json, 'collections' uses individual files
    source: 'theme',

    // Directory for raw Figma exports (theme.json or foundation.json, etc.)
    sourceDir: './src/figma-exports',

    // Base directory for processed collections (transform outputs to ./collections/ subdirs)
    collectionsDir: './src',

    // Output directory for generated files (CSS, SCSS, JS, TS)
    outputDir: './src/generated',

    // CSS variable prefix (e.g., --sb-color-blue-500)
    prefix: '--sb-',

    // Base font size for rem calculations
    baseFontSize: 16,

    // Output references in generated files (uses CSS var() functions)
    outputReferences: true,

    // Output formats to generate
    formats: ['css', 'js', 'ts', 'scss', 'json'],
  },
});
