sonar.projectKey=michelve_dsai
sonar.organization=epikly

sonar.sources=packages/@dsai-io/react/src,packages/@dsai-io/tools/src,packages/@dsai-io/figma-tokens/src
sonar.tests=packages/@dsai-io/react/src,packages/@dsai-io/tools/src,packages/@dsai-io/tools/test,packages/@dsai-io/figma-tokens/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/__tests__/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.stories.tsx,**/*.figma.tsx,**/storybook-static/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPaths=tsconfig.base.json
