/* eslint-disable security/detect-non-literal-fs-filename */
/**
 * React component generator
 *
 * Generates React icon components from optimized SVG data.
 *
 * @packageDocumentation
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { cleanSVGForReact } from '../core/parser.js';

import type {
  GeneratedIcon,
  GeneratorOptions,
  IconTemplate,
  IndexTemplate,
  OptimizedSVG,
  TypesTemplate,
} from '../types.js';

/**
 * Default React icon template
 *
 * Generates a forwardRef component with size, title, and aria support.
 */
export const defaultReactTemplate: IconTemplate = (icon) => {
  const cleanedContent = cleanSVGForReact(icon.innerContent);

  return `/**
 * ${icon.componentName} icon
 *
 * @generated by @dsai-io/tools
 */

import * as React from 'react';

import type { SVGProps } from 'react';

export interface ${icon.componentName}Props extends SVGProps<SVGSVGElement> {
  /** Icon size */
  size?: number | string;
  /** Icon title for accessibility */
  title?: string;
}

export const ${icon.componentName} = React.forwardRef<SVGSVGElement, ${icon.componentName}Props>(
  ({ size = 24, title${icon.title ? ` = "${icon.title}"` : ''}, ...props }, ref) => (
    <svg
      ref={ref}
      xmlns="http://www.w3.org/2000/svg"
      viewBox="${icon.viewBox}"
      width={size}
      height={size}
      fill="currentColor"
      aria-hidden={!title}
      aria-label={title}
      {...props}
    >
      {title && <title>{title}</title>}
      ${cleanedContent}
    </svg>
  )
);

${icon.componentName}.displayName = '${icon.componentName}';

export default ${icon.componentName};
`;
};

/**
 * Default React index template
 *
 * Exports all icon components from a single entry point.
 */
export const defaultReactIndexTemplate: IndexTemplate = (icons) => `/**
 * Icon exports
 *
 * @generated by @dsai-io/tools
 */

${icons.map((icon) => `export { ${icon.componentName} } from './${icon.componentName}.js';`).join('\n')}

// Re-export types
export type { SVGProps } from 'react';
`;

/**
 * Default React types template
 *
 * Generates TypeScript types for all icons.
 */
export const defaultReactTypesTemplate: TypesTemplate = (icons) => `/**
 * Icon types
 *
 * @generated by @dsai-io/tools
 */

import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react';

export interface IconProps extends SVGProps<SVGSVGElement> {
  size?: number | string;
  title?: string;
}

export type IconComponent = ForwardRefExoticComponent<
  IconProps & RefAttributes<SVGSVGElement>
>;

/**
 * Available icon names
 */
export type IconName =
${icons.map((icon) => `  | '${icon.name}'`).join('\n')};

/**
 * Icon component map
 */
export interface IconMap {
${icons.map((icon) => `  '${icon.name}': IconComponent;`).join('\n')}
}

/**
 * Icon metadata
 */
export interface IconMeta {
  name: IconName;
  componentName: string;
  viewBox: string;
}

export const iconMeta: IconMeta[] = [
${icons.map((icon) => `  { name: '${icon.name}', componentName: '${icon.componentName}', viewBox: '${icon.viewBox}' },`).join('\n')}
];
`;

/**
 * Generate React icon components
 *
 * @param icons - Optimized SVG data
 * @param outputDir - Output directory
 * @param options - Generator options
 * @returns Generated icons
 *
 * @example
 * ```typescript
 * const generated = await generateReactIcons(optimizedIcons, './dist/icons/react', {
 *   dryRun: false,
 * });
 * console.log(\`Generated \${generated.length} files\`);
 * ```
 */
export async function generateReactIcons(
  icons: OptimizedSVG[],
  outputDir: string,
  options: GeneratorOptions = {}
): Promise<GeneratedIcon[]> {
  const {
    template = defaultReactTemplate,
    indexTemplate = defaultReactIndexTemplate,
    typesTemplate = defaultReactTypesTemplate,
    dryRun = false,
  } = options;

  const generated: GeneratedIcon[] = [];

  // Ensure output directory exists
  if (!dryRun && !existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Generate individual icon components
  for (const icon of icons) {
    const code = template(icon);
    const outputPath = join(outputDir, `${icon.componentName}.tsx`);

    if (!dryRun) {
      writeFileSync(outputPath, code, 'utf-8');
    }

    generated.push({
      name: icon.name,
      componentName: icon.componentName,
      code,
      outputPath,
      format: 'react',
    });
  }

  // Generate index file
  const indexCode = indexTemplate(icons);
  const indexPath = join(outputDir, 'index.ts');

  if (!dryRun) {
    writeFileSync(indexPath, indexCode, 'utf-8');
  }

  generated.push({
    name: 'index',
    componentName: 'index',
    code: indexCode,
    outputPath: indexPath,
    format: 'react',
  });

  // Generate types file
  const typesCode = typesTemplate(icons);
  const typesPath = join(outputDir, 'types.ts');

  if (!dryRun) {
    writeFileSync(typesPath, typesCode, 'utf-8');
  }

  generated.push({
    name: 'types',
    componentName: 'types',
    code: typesCode,
    outputPath: typesPath,
    format: 'react',
  });

  return generated;
}
