/* eslint-disable security/detect-non-literal-fs-filename */
/**
 * SVG sprite generator
 *
 * Generates SVG sprite files with symbol definitions.
 *
 * @packageDocumentation
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { GeneratedIcon, OptimizedSVG } from '../types.js';

/**
 * SVG sprite generator options
 */
export interface SpriteOptions {
  /** Sprite file name */
  fileName?: string;

  /** Generate preview HTML file */
  generatePreview?: boolean;

  /** Dry run - don't write files */
  dryRun?: boolean;
}

/**
 * Generate SVG sprite
 *
 * Creates an SVG sprite with symbol definitions for all icons.
 *
 * @param icons - Optimized SVG data
 * @param outputDir - Output directory
 * @param options - Generator options
 * @returns Generated files
 *
 * @example
 * ```typescript
 * const generated = await generateSVGSprite(optimizedIcons, './dist/icons/sprite', {
 *   fileName: 'icons.svg',
 *   generatePreview: true,
 * });
 * ```
 */
export async function generateSVGSprite(
  icons: OptimizedSVG[],
  outputDir: string,
  options: SpriteOptions = {}
): Promise<GeneratedIcon[]> {
  const { fileName = 'sprite.svg', generatePreview = true, dryRun = false } = options;

  const generated: GeneratedIcon[] = [];

  // Ensure output directory exists
  if (!dryRun && !existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // Generate sprite symbols
  const symbols = icons
    .map(
      (icon) => `  <symbol id="${icon.name}" viewBox="${icon.viewBox}">
    ${icon.innerContent}
  </symbol>`
    )
    .join('\n');

  // Create sprite SVG
  const spriteCode = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  SVG Sprite
  @generated by @dsai/tools
  Contains ${icons.length} icons
-->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
${symbols}
  </defs>
</svg>
`;

  const outputPath = join(outputDir, fileName);

  if (!dryRun) {
    writeFileSync(outputPath, spriteCode, 'utf-8');
  }

  generated.push({
    name: 'sprite',
    componentName: 'sprite',
    code: spriteCode,
    outputPath,
    format: 'svg-sprite',
  });

  // Generate usage helper HTML
  if (generatePreview) {
    const usageCode = generatePreviewHTML(icons, fileName);
    const usagePath = join(outputDir, 'sprite-preview.html');

    if (!dryRun) {
      writeFileSync(usagePath, usageCode, 'utf-8');
    }

    generated.push({
      name: 'preview',
      componentName: 'preview',
      code: usageCode,
      outputPath: usagePath,
      format: 'svg-sprite',
    });
  }

  return generated;
}

/**
 * Generate preview HTML for sprite
 */
function generatePreviewHTML(icons: OptimizedSVG[], spriteFileName: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Icon Sprite Preview</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: system-ui, sans-serif; padding: 2rem; max-width: 1200px; margin: 0 auto; }
    h1 { margin-bottom: 0.5rem; }
    .meta { color: #666; margin-bottom: 2rem; }
    .icon { width: 24px; height: 24px; fill: currentColor; }
    .icon-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(100px, 1fr)); gap: 1rem; }
    .icon-item { display: flex; flex-direction: column; align-items: center; gap: 0.5rem; padding: 1rem; border: 1px solid #eee; border-radius: 8px; transition: background 0.2s; }
    .icon-item:hover { background: #f5f5f5; }
    .icon-name { font-size: 11px; color: #666; text-align: center; word-break: break-all; }
    pre { background: #f5f5f5; padding: 1rem; border-radius: 8px; overflow-x: auto; }
    code { font-family: ui-monospace, monospace; font-size: 13px; }
  </style>
</head>
<body>
  <h1>Icon Sprite Preview</h1>
  <p class="meta">${icons.length} icons • Generated by @dsai/tools</p>

  <h2>Usage</h2>
  <pre><code>&lt;svg class="icon"&gt;
  &lt;use href="${spriteFileName}#icon-name"&gt;&lt;/use&gt;
&lt;/svg&gt;</code></pre>

  <h2>All Icons</h2>
  <div class="icon-grid">
${icons
  .map(
    (icon) => `    <div class="icon-item">
      <svg class="icon"><use href="${spriteFileName}#${icon.name}"></use></svg>
      <span class="icon-name">${icon.name}</span>
    </div>`
  )
  .join('\n')}
  </div>
</body>
</html>
`;
}
