/**
 * SCSS Framework Variables Format
 *
 * Generates SCSS variables with framework-specific name mappings.
 * Transforms Figma token names to match target framework conventions.
 *
 * @packageDocumentation
 * @module @dsai-io/tools/tokens/style-dictionary/formats/scss-framework
 */

import { getFrameworkMapper, applyNameMapping } from '../../framework-mappers/mapper.js';

import type { FrameworkTarget } from '../../../config/types.js';
import type { SDFormatArgs, FormatDefinition } from '../types.js';

/**
 * Format options for scss/framework-variables
 */
export interface ScssFrameworkOptions {
  /**
   * Target framework for name mapping
   * @default 'bootstrap'
   */
  framework?: FrameworkTarget;

  /**
   * Custom name mappings to apply in addition to framework defaults
   * Key: original token name pattern, Value: mapped name
   */
  customMappings?: Record<string, string>;

  /**
   * Whether to output references for alias tokens
   * @default true
   */
  outputReferences?: boolean;

  /**
   * Variable prefix (without $)
   * @default ''
   */
  variablePrefix?: string;

  /**
   * Include header comment in output
   * @default true
   */
  includeHeader?: boolean;

  /**
   * Custom header comment
   */
  customHeader?: string;
}

/**
 * scss/framework-variables format
 *
 * Generates SCSS variables with framework-specific name mappings.
 * Supports Bootstrap, shadcn, and custom frameworks.
 *
 * @example
 * ```typescript
 * // In Style Dictionary config
 * {
 *   format: 'scss/framework-variables',
 *   options: {
 *     framework: 'bootstrap',
 *     customMappings: {
 *       'my-custom-token': 'bs-custom-var'
 *     }
 *   }
 * }
 * ```
 *
 * @example
 * Output for Bootstrap:
 * ```scss
 * // Generated by DSAi - Bootstrap 5.x compatible variables
 * // Do not edit manually - regenerate with: pnpm tokens:build
 *
 * $font-size-base: 1rem;
 * $headings-font-weight: 600;
 * $primary: #007bff;
 * ```
 */
export const scssFrameworkVariables: FormatDefinition = {
  name: 'scss/framework-variables',
  format: ({ dictionary, options }: SDFormatArgs): string => {
    const framework = (options['framework'] as FrameworkTarget) ?? 'bootstrap';
    const customMappings = (options['customMappings'] as Record<string, string>) ?? {};
    const variablePrefix = (options['variablePrefix'] as string) ?? '';
    const includeHeader = (options['includeHeader'] as boolean) ?? true;
    const customHeader = options['customHeader'] as string | undefined;

    // Get framework mapper
    const mapper = getFrameworkMapper(framework);

    // Build header
    const lines: string[] = [];

    if (includeHeader) {
      if (customHeader) {
        lines.push(customHeader);
      } else {
        lines.push(
          mapper.config.header || `// ${framework} variables generated by DSAi`,
          '// Do not edit manually - regenerate with: pnpm tokens:build',
          ''
        );
      }
    }

    // Process each token
    for (const token of dictionary.allTokens) {
      // Apply framework name mapping
      const mappedName = applyNameMapping(token.name, framework, customMappings);

      // Format the mapped name: remove dashes and apply prefix
      const scssVarName = `$${variablePrefix}${mappedName}`;

      // Get token value (DTCG format uses $value)
      const tokenValue = token.$value ?? token.value;
      const value = typeof tokenValue === 'string' ? tokenValue : JSON.stringify(tokenValue);

      // Add description comment if present
      const description = token.$description ?? token.description;
      if (description) {
        lines.push(`// ${description}`);
      }

      // Add the variable
      lines.push(`${scssVarName}: ${value};`);
    }

    return lines.join('\n') + '\n';
  },
};

/**
 * scss/bootstrap-variables format
 *
 * Convenience format that uses Bootstrap mappings by default.
 *
 * @example
 * ```typescript
 * {
 *   format: 'scss/bootstrap-variables'
 * }
 * ```
 */
export const scssBootstrapVariables: FormatDefinition = {
  name: 'scss/bootstrap-variables',
  format: (args: SDFormatArgs): string => {
    const optionsWithBootstrap = {
      ...args.options,
      framework: 'bootstrap' as FrameworkTarget,
    };
    return scssFrameworkVariables.format({ ...args, options: optionsWithBootstrap });
  },
};

/**
 * scss/shadcn-variables format
 *
 * Convenience format that uses shadcn/ui mappings by default.
 * Outputs CSS custom properties in SCSS for compatibility.
 *
 * @example
 * ```typescript
 * {
 *   format: 'scss/shadcn-variables'
 * }
 * ```
 */
export const scssShadcnVariables: FormatDefinition = {
  name: 'scss/shadcn-variables',
  format: (args: SDFormatArgs): string => {
    const optionsWithShadcn = {
      ...args.options,
      framework: 'shadcn' as FrameworkTarget,
    };
    return scssFrameworkVariables.format({ ...args, options: optionsWithShadcn });
  },
};
